from django.urls import path, include
from . import views
from rest_framework.routers import DefaultRouter
from .views import MemoViewSet

# Create a router and register viewset with it
router = DefaultRouter()
router.register(r'memos', MemoViewSet)  # Register the MemoViewSet underr 'memos' endpoint


urlpatterns = [
    path('', views.index,name="index"),
    path('addnewmemo/', views.add,name="add"),
    path('addrec/', views.addrec,name="addrec"),
    path('delete/<int:id>/', views.delete, name="delete"),
    path('update/<int:id>/', views.update, name="update"),
    path('update/uprec/<int:id>/', views.uprec, name="uprec"),
    path('api/', include(router.urls)), # for Restful apis usually, include used by URLS generated by router
]