# Generated by Django 5.1 on 2024-08-19 09:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Memos',
            new_name='Memo',
        ),
    ]
