# Generated by Django 5.1.1 on 2024-10-08 00:37

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0002_rename_memos_memo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='memo',
            old_name='name',
            new_name='title',
        ),
        migrations.AddField(
            model_name='memo',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
